[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/waitlist"
  to = "/.netlify/functions/waitlist"
  status = 200
  force = true

[[redirects]]
  from = "/api/waitlist-export"
  to = "/.netlify/functions/waitlist_export"
  status = 200
  force = true
